[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pulp-docs"
version = "0.0.1"
readme = "README.md"
description = "Tool to aggregate Pulp documentation in one place."
dependencies = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-macros-plugin",
    "mkdocs-site-urls",
    "importlib_resources",
    "httpx",
    "rich",
]

[project.scripts]
pulp-docs = "pulp_docs.cli:main"

[tool.setuptools]
include-package-data=true

[tool.setuptools.package-data]
pulp_docs = ["data/**"]

[tool.setuptools.packages.find]
where = ["src"]

