name: "Update Data Branch"

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: docs-data

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: "List requirements"
        run: |
          cat requirements_system.txt
          cat requirements_python.txt

      - name: "Install System dependencies"
        run: |
          xargs sudo apt -y install < requirements_system.txt
          sudo apt -y install gir1.2-ostree-1.0  # required by ostree

      - name: "Install Python dependencies"
        run: |
          pip install --upgrade pip
          pip install -r requirements_python.txt

      - name: "Generate, commit and push updated openapi specs"
        run: |
          ./update-data.sh
